FROM ubuntu:14.04
MAINTAINER R Sloan "rnsloan1@gmail.com"
ENV REFRESHED_AT 2015-05-11

RUN apt-get -y --fix-missing update
RUN apt-get -y install build-essential
RUN apt-get -y install valgrind
RUN apt-get -y install man-db
